name: Val
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        git fetch --prune

        echo "## Model metrics" > report.md
        dvc metrics show --show-md >> report.md
          
        echo "## Best batch predictions" >> report.md
        cml-publish experiment/best_batch.jpg --md >> report.md
        echo "## Worst batch predictions" >> report.md
        cml-publish experiment/worst_batch.jpg --md >> report.md
          
        cml-send-comment report.md