name: Val

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        git fetch --prune

    - name: Generate report
      run: |
        echo "## Model metrics" > report.md
        dvc metrics show --show-md >> report.md
          
        echo "## Best batch predictions" >> report.md
        cml-publish experiment/best_batch.jpg --md >> report.md
        echo "## Worst batch predictions" >> report.md
        cml-publish experiment/worst_batch.jpg --md >> report.md
          
        cml-send-comment report.md