name: Val

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "dvc[gdrive]"

    - name: DVC pull
      run: dvc pull -r data
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

    - name: Generate report
        run: |
          echo "## Model metrics" > report.md
          cat experiment/loss.json >> report.md
          
          echo "## Data visualization" >> report.md
          cml-publish experiment/best_batch.jpg --md >> report.md
          cml-publish experiment/worst_batch.jpg --md >> report.md
          
          cml-send-comment report.md